### PR TITLE
Replace completeness multitasker with d4tools perc_cov

### LINKED ISSUE #316: Improve performance of get_coverage_completeness.py
As discussed in [#299](https://github.com/Clinical-Genomics/chanjo2/issues/299), the current performance bottleneck seems to be the get_coverage_completeness.py function. If we could resolve this, it would be great for the Chanjo2 usability.

It is both something that would make the switch to Chanjo2 more smooth and an interesting problem.

Here is a snakeviz profiling from running ~70 intervals with three thresholds (10, 20, 30). It seems to me most time is spend parsing output from the d4tools view output

image

I also tried using the d4tools stat -stat hist output and checking the fraction at or above specific thresholds. This seemed to give correct values, but processing time is similar - again time spent at parsing output from the command.

```
        command = f"bash -c \"{D4_TOOLS} stat --stat hist --region <(echo '{coords[0]} {coords[1]} {coords[2]}' | tr ' ' '\t') {d4_file_path}\""
        hist_results: List[str] = subprocess.check_output(
            "".join(command),
            shell=True,
            text=True,
        ).splitlines()

        hist_results_num_bin = [[int(pair.split()[0]), int(pair.split()[1])] for pair in hist_results[1:-1]]
        total = sum([pair[1] for pair in hist_results_num_bin])
        for threshold in thresholds:
            threshold_sum = sum([pair[1] for pair in hist_results_num_bin if pair[0] >= threshold])
            print(f"sum {total} threshold {threshold_sum} above {threshold_sum / total}")
```
It spontaneously looks to me that the ideal solution would be to get in a new stat function into d4tools which runs similarly to the mean calculations - giving an output as such:

```
$ d4tools stat --stat cov_at_thres --thresholds 10 20 30
chr    start    end     perc_thres1     perc_thres2     perc_thres3
```

This should be much quicker, but unsure how smooth it would be technically and socially to squeeze it into d4tools 🤔 Maybe worth raising an issue, if we think this is the way to go.

Otherwise it seems we would like somehow directly read from the d4 file using code in the d4tool. Probably feasible as well. Not sure how to package this in a non-messy way though.

Might be a good starting point to just fork d4tools and see if we could get it to do what we want here and see the performance. If it works, then think about how to package this.

Do you have thoughts on this?

Needless to say, this would be useful for us and I am happy to help 🙂

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added/Changed/Fixed
- Closes #316

### How to test
- [x] Deploy on stage and compare coverage completeness results with main branch

### Expected outcome
- Stats from using this branch should be quicker

## Review
- [x] Tests executed by CR, Jakob37
- [ ] "Merge and deploy" approved by Jakob37

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Test with a scout case and OMIM-AUTO panel (4637 genes)

### Main branch on stage: -> report created in about 120 seconds:

image


### This test on stage -> report created in 13 seconds

image

So the report creating is about 10 times faster when using the perc_cov from d4tools. The numbers are the same, but not the percentage of fully covered genes (compare the 2 screeshots). I'll check which one is correct!

**Comment by northwestwitch** [comment]
> **So the report creating is about 10 times faster when using the perc_cov from d4tools.** The numbers are the same, but not the percentage of fully covered genes (compare the 2 screenshots). I'll check which one is correct!

I've compared the results with a real d4 locally but less genes, main branch and this branch give exactly the same results. The code for computing of the percentage of the fully covered genes hasn't changed in this PR so I assume it must be the changes in the stats over the intervals. The python method and the d4tools perc_cov might give slightly different results, and if for instance in one method you get coverage completeness 99,99999 instead of 1, then the gene interval will count as not covered. I'll test with more gene panels

**Comment by Jakob37** [comment]
Cool to see this moving! Close to goal now :D 

One thing I wanted to ask. Are you handling that the output format sometimes comes in scientific notation and somtimes in numeric?

I think in the end, the logic is like this:

* If > 0.001, then `0.230` format
* If < 0.001, then `1.34e-5` format (this will also apply to `== 0` I think, not perfect, but I didn't had the heard to squeeze cardemich for any more updates)

**Comment by northwestwitch** [comment]
> Are you handling that the output format sometimes comes in scientific notation and somtimes in numeric?

The output from d4tools you mean?

**Comment by Jakob37** [comment]
> > Are you handling that the output format sometimes comes in scientific notation and somtimes in numeric?
> 
> The output from d4tools you mean?

Yes. Here is how the test output looks now:

https://github.com/38/d4-format/blob/master/d4tools/test/stat/perc_cov-multiple-ranges/output.txt

```
chr	0	2	0.000e0	0.000e0
chr	0	8	0.625	0.375
chr	0	10	0.600	0.300
chr	1	6	0.600	0.400
chr	3	9	1.000	0.500
chr	4	5	1.000	1.000
chr	5	10	0.800	0.400
```

(No cases `> 0 && < 0.001` here unfortunately, but that would be `e` syntax as well)

**Comment by Jakob37** [comment]
> I've compared the results with a real d4 locally but less genes, main branch and this branch give exactly the same results. The code for computing of the percentage of the fully covered genes hasn't changed in this PR so I assume it must be the changes in the stats over the intervals. The python method and the d4tools perc_cov might give slightly different results, and if for instance in one method you get coverage completeness 99,99999 instead of 1, then the gene interval will count as not fully covered. I'll test with more gene panels

Hmm. I'll see if I can test this a bit as well.

**Comment by northwestwitch** [comment]
mmm in theory the scientific notation should be takes care of in line 32 of src/chanjo2/meta/handle_completeness_stats.py, when it gets converted to float..

**Comment by northwestwitch** [comment]
Mmm there is something weird with some genes for this branch. For instance I have a panel with 44 genes:

Main branch report:

image

Note that BRAFP1 is not fully coverered.

Same report with this branch:

image

BRAFP1 seems fully covered at 10X

But it's obviously not, because when you check the coverage for just that gene you get this

image

**Comment by Jakob37** [comment]
Hmm, has the expected format for the report end-point changed?

This command has worked for me before:

```
curl -X 'POST' \
  'http://localhost:9000/report' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "build": "GRCh38",
  "hgnc_gene_ids": [2933,6842,10447,11947],
  "interval_type": "genes",
  "default_level": 10,
  "panel_name": "Custom panel",
  "case_display_name": "Test sample",
  "samples": [
    {
      "name": "string",
      "coverage_file_path": "/home/worker/app/data/hg002.d4",
      "case_name": "Test case",
      "analysis_date": "2023-10-04T08:22:06.980106"
    }
  ]
}'
```

I'll continue digging, but suspecting this is something obvious :)

**Comment by northwestwitch** [comment]
> Hmm, has the expected format for the report end-point changed?
> 
> This command has worked for me before:
> 
> ```
> curl -X 'POST' \
>   'http://localhost:9000/report' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "build": "GRCh38",
>   "hgnc_gene_ids": [2933,6842,10447,11947],
>   "interval_type": "genes",
>   "default_level": 10,
>   "panel_name": "Custom panel",
>   "case_display_name": "Test sample",
>   "samples": [
>     {
>       "name": "string",
>       "coverage_file_path": "/home/worker/app/data/hg002.d4",
>       "case_name": "Test case",
>       "analysis_date": "2023-10-04T08:22:06.980106"
>     }
>   ]
> }'
> ```
> 

Yes, I removed the support for json requests, so it accepts only x-www-form-urlencoded form data (same requests that are sent from Scout). I did this with the idea that the "coverage" endpoint should accept json instead.

Could you try this request instead?

```
curl -X 'POST' \
  'http://localhost:9000/report' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'build=GRCh38' \
  -d 'hgnc_gene_ids=2933' \
  -d 'hgnc_gene_ids=6842' \
  -d 'hgnc_gene_ids=10447' \
  -d 'hgnc_gene_ids=11947' \
  -d 'interval_type=genes' \
  -d 'default_level=10' \
  -d 'panel_name=Custom panel' \
  -d 'case_display_name=Test sample' \
  -d 'samples[0][name]=string' \
  -d 'samples[0][coverage_file_path]=/home/worker/app/data/hg002.d4' \
  -d 'samples[0][case_name]=Test case' \
  -d 'samples[0][analysis_date]=2023-10-04T08:22:06.980106' 
```

**Comment by Jakob37** [comment]
Thanks! That put me on the right track. This worked:

```
curl -X POST http://localhost:9000/report \
  -H "Accept: application/json" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "build=GRCh38" \
  -d "hgnc_gene_ids=2933,6842,10447,11947" \
  -d "interval_type=genes" \
  -d "default_level=10" \
  -d "panel_name=Custom panel" \
  -d "case_display_name=Test sample" \
  -d 'samples=[{"name":"string","coverage_file_path":"/home/worker/app/data/hg002.d4","case_name":"Test case","analysis_date":"2023-10-04T08:22:06.980106"}]'
```

**Comment by northwestwitch** [comment]
Ah I just found the bug. d4tools changes the order of the provided intervals and writes a result file ordered by chrom, start and stop. So I have to take care of this. Will fix!

**Comment by northwestwitch** [comment]
Ok the fix that I've just pushed cover the BRAFP1 problem described above. The gene now shows:

image

But the number of fully covered genes is still different from main branch. I'll debug some more 🤔

**Comment by Jakob37** [comment]
I have the new version up and running now on our dev server.

Looking on a previous case. This does not look right 🤔 

chanjo2_test

**Comment by northwestwitch** [comment]
> Edit: Numbers are low (and plausible) for a single gene, but go crazy when two genes are studied at the same time.

Woa, that's a lot of coverage! 😆 
I get more of less the same values as before, the only number slightly changed is the fully covered genes. Are you sure you are on this branch and its latest version? I had a pair of other branches where I started to address this change that now are gone

**Comment by Jakob37** [comment]
Hmmm. I will check, but I think I am in the right place. And also, I get some concerning numbers from d4tools itself:

```
worker@8f332e90467a:~/app$ d4tools stat -s perc_cov=10,15,20,50,100 --region /tmp/tmpy6598chg /fs1/results_dev/wgs/cov/<id>-d4_wgs_1_coverage.d4 -H
#Chr    Start       End         10x     15x     20x     50x     100x
12      21797389    21942543    0.123   0.113   0.102   0.010   0.000e0
17      7217125     7225266     339.552 339.512 339.474 0.179   0.000e0
```

**Comment by northwestwitch** [comment]
> worker@8f332e90467a:~/app$ d4tools stat -s perc_cov=10,15,20,50,100 --region /tmp/tmpy6598chg /fs1/results_dev/wgs/cov/<id>-d4_wgs_1_coverage.d4 -H
> #Chr    Start       End         10x     15x     20x     50x     100x
> 12      21797389    21942543    0.123   0.113   0.102   0.010   0.000e0
> 17      7217125     7225266     339.552 339.512 339.474 0.179   0.000e0

Ok. Are you using the latest main branch from d4tools, perhaps you didn't update or something?

**Comment by Jakob37** [comment]
> > worker@8f332e90467a:~/app$ d4tools stat -s perc_cov=10,15,20,50,100 --region /tmp/tmpy6598chg /fs1/results_dev/wgs/cov/-d4_wgs_1_coverage.d4 -H
> > #Chr    Start       End         10x     15x     20x     50x     100x
> > 12      21797389    21942543    0.123   0.113   0.102   0.010   0.000e0
> > 17      7217125     7225266     339.552 339.512 339.474 0.179   0.000e0
> 
> Ok. Are you using the latest main branch from d4tools, perhaps you didn't update or something?

The code above is executed inside the Chanjo2 container, so if the container is up to date, the command above would be.

I'll test around some more.

**Comment by Jakob37** [comment]
Hmm, running the same ranges for other datasets, things seem to look fine. The one above is one of the first d4-files I created, so maybe something was weird back then. 

Looks fine for a whole bunch of others:

```
12      21797389        21942543        0.122   0.111   0.099   0.006   0.000e0
17      7217125 7225266 0.910   0.864   0.809   0.149   0.000e0
12      21797389        21942543        0.123   0.111   0.101   0.006   0.000e0
17      7217125 7225266 0.918   0.873   0.820   0.228   0.000e0
12      21797389        21942543        0.124   0.114   0.103   0.008   0.000e0
17      7217125 7225266 0.912   0.874   0.824   0.135   0.000e0
12      21797389        21942543        0.132   0.125   0.119   0.079   0.000e0
17      7217125 7225266 0.942   0.927   0.898   0.700   0.000e0
12      21797389        21942543        0.127   0.118   0.108   0.025   0.000e0
17      7217125 7225266 0.923   0.886   0.849   0.239   0.000e0
12      21797389        21942543        0.117   0.102   0.089   5.511e-5        0.000e0
17      7217125 7225266 0.884   0.816   0.736   0.000e0 0.000e0
12      21797389        21942543        0.124   0.113   0.102   0.007   0.000e0
17      7217125 7225266 0.903   0.849   0.794   0.096   0.000e0
12      21797389        21942543        0.994   0.993   0.990   0.212   0.000e0
17      7217125 7225266 1.000   0.983   0.959   0.284   0.000e0
```

I'll continue testing, but slightly less concerned now.

**Comment by Jakob37** [comment]
OK, I could reproduce it for that specific d4-file after compiling and running the latest version of d4tools locally.

But I cannot reproduce it for any other files.

I suspect I indexed the d4files in the beginning in our pipeline. And that this is related to that (https://github.com/38/d4-format/issues/80). Later I removed the indexing, which fits with that all later samples look OK.

**Comment by Jakob37** [comment]
More testing. Here is the report for a real case:

case

Inside the Chanjo2 container, I can confirm that the numbers check out:

```
$ d4tools stat -s perc_cov=10,15,20,50,100 --region /tmp/tmpwsbck5aw /access/wgs/cov/24MD10978_coverage.d4 > /tmp/out.txt
$ wc -l /tmp/out.txt
71
$ cat /tmp/out.txt | cut -f4 | grep -v "1.000" | wc -l
34
```

**Comment by Jakob37** [comment]
More testing. Here is the report for a real case:

case

Inside the Chanjo2 container, I can confirm that the numbers fully covered genes check out:

```
$ d4tools stat -s perc_cov=10,15,20,50,100 --region /tmp/tmpwsbck5aw /access/wgs/cov/<ID>_coverage.d4 > /tmp/out.txt
$ wc -l /tmp/out.txt
71
$ cat /tmp/out.txt | cut -f4 | grep -v "1.000" | wc -l
34
```

**Comment by northwestwitch** [comment]
> Inside the Chanjo2 container, I can confirm that the numbers fully covered genes check out:

That's also what I'm seeing with our demo case. Looks like that 100% covered genes are the same in chanjo2 and d4tools

**Comment by northwestwitch** [comment]
And it's faster right?

**Comment by Jakob37** [comment]
> And it's faster right?

I timed a case now with 680 IDs. It loaded the page in ~40 seconds.

Running just the d4-part it finished in 6 seconds, which is much faster than before.

So looks like the bottleneck has shifted somewhere else now.

But I think ~40 seconds will be acceptible loading time for the geneticists ...

**Comment by Jakob37** [comment]
I think it looks great, looking forward to finally put this into action 👌

**Comment by northwestwitch** [comment]
> But I think ~40 seconds will be acceptible loading time for the geneticists ...

I think so too. And I know there is room for improvement. This PR was meant to be a non-invasive and potentially problematic alternative to the code we have on main branch. Shall I merge?

**Comment by Jakob37** [comment]
Yes, let's merge 🎉

**Review by Jakob37 — APPROVED** [review]
Worked nicely in testing. Didn't see anything to mention when eyeing through the code.
Nice 👌

**Pull request merged**
