### PR TITLE
Fix cov stats by running b4tools stat for each line of a bed file

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- This is a working version of the fix. #302 is an alternative solution

**How to prepare for test**:
- [ ] `ssh` to ...
- [ ] Install on stage:
`bash servers/resources/SERVER.scilifelab.se/update-[THIS_TOOL]-stage.sh [THIS-BRANCH-NAME]`

### How to test:
-

### Expected outcome:
- [ ]

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Checked again this solution (after [fixing the error](https://github.com/Clinical-Genomics/chanjo2/pull/302#discussion_r1613018934)) and it takes minutes to run. For a panel with 4K> genes times out eventually:

image

So I guess this is not a solution 😭

**Comment by Jakob37** [comment]
> Checked again this solution (after [fixing the error](https://github.com/Clinical-Genomics/chanjo2/pull/302#discussion_r1613018934)) and it takes minutes to run. For a panel with 4K+ genes times out eventually:
> image
> 
> So I guess this is not a solution after all 😭

Aha oh no :( Guess that explains how it could be faster ..

Then I guess we will need to focus on getting d4tools in shape!

**Comment by northwestwitch** [comment]
> Then I guess we will need to focus on getting d4tools in shape!

I think so. Even if this is not the first bug they have 😩

**Comment by northwestwitch** [comment]
Closing

**Comment by Jakob37** [comment]
> > Then I guess we will need to focus on getting d4tools in shape!
> 
> I think so. Even if this is not the first bug they have 😩

Yes, a bit unfortunate that the dev speed seems so slow over there ..

**Pull request closed without merging**
