### PR TITLE
Major release 2.0

### PR DESCRIPTION
**Pull request by northwestwitch**
### Added
- Improve report explanation to better interpret average coverage and coverage completeness stats shown on the coverage report
- Check that provided d4 files when running queries using `/coverage/d4/genes/summary` endpoint are valid, with test
- General report with coverage over the entire genome when no genes or genes panels are provided
- A MANE coverage report, showing coverage and coverage completeness only on MANE transcripts for the provided list of genes
- Link out from MANE overview to gene overview
- Save ensembl_transcript_id and exon rank info on exons database records
- Display MANE badges on gene overview report
- `Create PDF` button on MANE overview and gene overview pages
- Documentation on how to create MANE overview reports
### Changed
- Do not use stored cases/samples any more and run stats exclusively on d4 files paths provided by the user in real time
- How parameters are passed to starlette.templating since it was raising a deprecation warning.
- Replaced deprecated Pydantic `parse_obj` method with `model_validate`
- Report and genes overview endpoints accept only POST requests with form data now (application/x-www-form-urlencoded) - no json
- Sort alphabetically the list genes that are incompletely covered on report page
- `d4_genes_condensed_summary` coverage endpoint will not convert `nan` or `inf` coverage values to None, but to str(value)
- Updated the Dockerfile base image so it contains the latest d4tools (master branch)
- Updated tests workflow to cargo install the latest d4tools from git (master branch)
- Computing coverage completeness stats using d4tools `perc_cov` stat function (much quicker reports)
- Moved functions computing the coverage stats to a separate `meta/handle_coverage_stats.py` module
- Refactored code collecting stats shown on gene overview report
- Gene report to contain both transcripts and exons stats
### Fixed
- Updated dependencies including `certifi` to address dependabot alert
- Update pytest to v.7.4.4 to address a `ReDoS` vulnerability
- Colored logs
- Link for switching between coverage thresholds on overview report
- Gene links in genes overview page open into new tabs

## Review
- [ ] Tests executed by CR and Jakob37 
- [ ] "Merge and deploy" approved by

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
@Jakob37 I think we might be more or less ready with a new major. Are we missing anything?

**Comment by Jakob37** [comment]
> @Jakob37 I think we might be more or less ready with a new major. Are we missing anything?

Nice 🎉 No, I can't come up with anything clearly missing.

I can give it a test run after lunch!

**Comment by northwestwitch** [comment]
> Nice 🎉 No, I can't come up with anything clearly missing.
> 
> I can give it a test run after lunch!

Thanks! I think I'll just create the release. We kind of tested all the items in the list anyway

**Comment by Jakob37** [comment]
I deployed and tested now. Looks good, same as in prior testing!

Nice work 💪 Long journey, hopefully d4tools will behave from now on.

Out of curiousity. Do you know when the clinicians in Stockholm plan to start using Chanjo2?

**Comment by northwestwitch** [comment]
> I deployed and tested now. Looks good, same as in prior testing!
> 
> Nice work 💪 Long journey, hopefully d4tools will behave from now on.
> 
> Out of curiousity. Do you know when the clinicians in Stockholm plan to start using Chanjo2?

Nice! Thanks for the help! I'm sure that there will be updates and fixes to be applied but feels good to have something workable, finally!

Our clinicians will start using it as soon as it goes into production. The issue is creating the d4tools files in the pipeline (I think we are at a good point with this) and fix out software "cg" to add the path to these d4tools files into the scout confix file - I'll add it on their to do list. I guess soon. I'll let you know about our progress and the feedback from our clinicians!

**Comment by Jakob37** [comment]
> Nice! Thanks for the help! I'm sure that there will be updates and fixes to be applied but feels good to have something workable, finally!

😄 

> Our clinicians will start using it as soon as it goes into production. The issue is creating the d4tools files in the pipeline (I think we are at a good point with this) and fix out software "cg" to add the path to these d4tools files into the scout config file - I'll add it on their to do list. I guess soon. I'll let you know about our progress and the feedback from our clinicians!

Sounds good!

**Comment by northwestwitch** [comment]
I forgot to mention that this will go in production as soon as the
nf-core/raredisease will go in production. I'm not sure when it will be

**Pull request merged**
