### PR TITLE
Do not save cases/samples into the sql database and work uniquely with stats runned on d4 files on the fly 

### LINKED ISSUE #329: Simplify app by not saving cases and samples into the database
Doesn't look like we are going to use this feature anyway.

This change is going to be a major

### PR DESCRIPTION
**Pull request by northwestwitch**
### THIS IS A MAJOR CHANGE, 
but with the refactoring of the computation of the coverage completeness (upcoming PR), why can't we release a mayor? It's good timing.

### Changed
- Do not save cases/samples into the sql database and work uniquely with stats runned on d4 files on the fly (closes #329 )

Currently chanjo2 supports saving cases and samples (including paths to local d4 files) data into the database for later use. Later use being the following endpoints:
- [Gene coverage/completeness from case name or sample name]( https://github.com/Clinical-Genomics/chanjo2/blob/4515b79355f9b163147cada54b653d848cbe1c58/src/chanjo2/models/pydantic_models.py#L187) 
- [Transcripts coverage/completeness from case name or sample name](https://github.com/Clinical-Genomics/chanjo2/blob/4515b79355f9b163147cada54b653d848cbe1c58/src/chanjo2/endpoints/coverage.py#L259)
- [Exons coverage/completeness from case name or sample name](https://github.com/Clinical-Genomics/chanjo2/blob/4515b79355f9b163147cada54b653d848cbe1c58/src/chanjo2/endpoints/coverage.py#L292)

None of the functionalities are used by us or our collaborators, so I want to simplify chanjo2 by removing them.

### How to test
- [x] All automatic tests should run as expected
- [x] Deploy on stage and use a scout case to retrieve coverage report

### Expected outcome
- Case report from scout case should work as expected

## Review
- [x] Tests executed by CR, JW
- [x] "Merge and deploy" approved by JW

### This [version](https://semver.org/) is a
- [x] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
Hi @Jakob37. I was wondering if you have some time to give this PR a review? It's not adding any new feature, only removing stuff we are not using (see PR description) thus simplifying the whole thing. Thanks!

**Comment by Jakob37** [comment]
> Hi @Jakob37, I was wondering if you have some time to give this PR a review? It's not adding any new feature, only removing stuff we are not using (see PR description) thus simplifying the whole thing. Thanks!

Yes, I can take a look before the end of this week!

**Comment by Jakob37** [comment]
I ran this locally together with the Scout stack. The latest main branch of Scout.

I needed to mount in the Scout demo data folder to get it working - before that Chanjo2 couldn't access the d4 file. But that is probably as expected.

Looks good!

new_chanjo2

**Review by Jakob37 — APPROVED** [review]

**Comment by Jakob37** [comment]
I eyed through the code as well. Didn't find anything to comment on there. This seems to simplify the code a lot, nice 😄

**Comment by northwestwitch** [comment]
> I eyed through the code as well. Didn't find anything to comment on there. This seems to simplify the code a lot, nice 😄

Thank you! Let's go for this and a new major release when we have the new faster completeness stats in place!

**Pull request merged**
