### PR TITLE
Pydantic 2

### LINKED ISSUE #165: Switch to pydantic2
So far it is OK, because the dependency is defined like this on the poetry.lock:

pydantic = ">=1.6.2,<1.7 || >1.7,<1.7.1 || >1.7.1,<1.7.2 || >1.7.2,<1.7.3 || >1.7.3,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0"

But let's keep this in mind when upgrading!

### PR DESCRIPTION
**Pull request by northwestwitch**
### This PR adds | fixes:
- Upgrade Fastapi and Pydantic libs to the latest available (closes #165 )
- Modify code to support Pydantic 2 validations 

### How to test:
- Automatic tests should pass
- Launch locally and make sure docs for the endpoints are served

### Review:
- [x] Code approved by HS
- [x] Tests executed by GitHub actions & CR

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

### CODE REVIEW

**Comment by northwestwitch** [comment]
This is ready for review now!

**Comment by northwestwitch** [comment]
Tested OK locally:

image

**Review by henrikstranneheim — APPROVED** [review]
Nice 👍

**Comment by northwestwitch** [comment]
> Nice 👍

Thanks for the review! 🙏🏻  Before merging I'd like to merge [this PR](https://github.com/Clinical-Genomics/schug/pull/62) and create a new release of schug so I can update its version in the requirements of chanjo2.

**Pull request merged**
